TCCgo/TCCgo/apps/core/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

TCCgo/TCCgo/apps/faq/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns = [
    # views.faq - funcao no arquivo view.py
    url(r'^$', views.faq_page, name='faqs'),

    url(r'^all_questions', views.get_all_questions, name='get_all_questions'), 
]

TCCgo/TCCgo/apps/forum/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', login_required(views.forum_page), name='forum'),
    url(r'^new_topic',login_required(views.new_topic), name='new_topic'),
    url(r'^create_topic',login_required(views.create_topic), name='create_topic'),
    url(r'^filter_topics', login_required(views.filter_topics), name='filter_topics'),
    url(r'^view_topic', login_required(views.view_topic), name='view_topic'),
    url(r'^all_topics', login_required(views.get_all_topics), name='all_topics'),
    url(r'^get_topic', login_required(views.get_topic), name='get_topic'),
    url(r'^get_user',login_required(views.get_user), name='get_user'),
    url(r'^create_post',login_required(views.create_post), name='create_post'),
    url(r'^get_posts', login_required(views.get_posts), name='get_posts'),

]

TCCgo/TCCgo/apps/rules/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', login_required(views.rules_list), name='rules_list'), # List all the rules of the user

    # login required ->
    # Ajax requests urls
    url(r'^all_rules', login_required(views.get_all_rules), name='get_all_rules'), # Get all user rules
    url(r'^all_type', login_required(views.get_all_types), name='get_all_types'), # Get all rules types existent
    url(r'^create_rule', login_required(views.create_rule), name='create_rule'), # Create a new rule from a post form
    url(r'^verify_name', login_required(views.verify_name), name='verify_name'), # Verify if a given name already exists in database
    url(r'^delete_rule', login_required(views.delete_rule), name='delete_rule'), # Delete a rule passed in the request
    url(r'^filter_rules', login_required(views.filter_rules), name='filter_rules'), # Return a filtered set of rules
    url(r'^update_rule', login_required(views.update_rule), name='update_rule'), # Update a rule with the send data

    # public urls


]

TCCgo/TCCgo/apps/text/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # URL DE TESTE

    url(r'^submit_page', login_required(views.text_page), name='submit_page'), # page: submit text
    url(r'^submit', login_required(views.create_text), name='submit'), # create text, action of submit (post)
    url(r'^all_texts', login_required(views.get_all_texts), name='all_texts'), # return get all texts (get)
    url(r'^list_texts', login_required(views.all_texts_page), name='list_texts'), # page: list all texts
    url(r'^filter_texts', login_required(views.filter_texts), name='filter_texts'), # return a filtered set of rules (get)
    url(r'^delete_text', login_required(views.delete_text), name='delete_text'), # delete text (post / ajax)
    url(r'^edit_text/', login_required(views.edit_text_page), name='edit_text'),
    url(r'^update_text', login_required(views.update_text), name='update_text'),
    url(r'^get_text', login_required(views.get_text), name='get_text'),
    url(r'^processing_text', login_required(views.processing_text_page), name='processing_text'),
    url(r'^get_processed_text', login_required(views.get_processed_text), name='get_processed_text'),
    url(r'^fix_text', login_required(views.fix_text), name='fix_text')
]

TCCgo/TCCgo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', include('TCCgo.apps.core.urls', namespace='core')), # Main application
    url(r'^auth/', include('TCCgo.apps.authentication.urls', namespace='authentication')), # Authentication application
    url(r'^rules/', include('TCCgo.apps.rules.urls', namespace='rules')), # Rules management
    url(r'^faqs/', include('TCCgo.apps.faq.urls', namespace='faqs')),
    url(r'^forum/', include('TCCgo.apps.forum.urls', namespace='forum')),
    url(r'^text/', include('TCCgo.apps.text.urls', namespace='text')),
]

TCCgo/TCCgo/apps/faq/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	#dar migrate cria db
	question = models.CharField(max_length = 255)#maxlength, unique
	answer = models.CharField(max_length = 255)#maxlength, unique

TCCgo/TCCgo/apps/faq/controller.py
from .models import Question

class QuestionController(object):
    def create(question, answer):
        """ Create a question and save it to the database."""
        new_question = Question(question=question, answer = answer)
        new_question.save()
        print("Questão salva no banco de dados")
        return new_question

    def get_all():
        questions = Question.objects.all()
        return questions

TCCgo/TCCgo/apps/faq/views.py
import json
from django.shortcuts import render
from django.http import JsonResponse
#from django.http import HttpResponse
from django.core import serializers

from .controller import QuestionController
#from .models import Question

# Create your views here.
def get_all_questions(request):
	query_set = QuestionController.get_all()
	data = serializers.serialize('json', query_set)
	#print data
	return JsonResponse(data, safe=False)

def faq_page(request):
	return render(request, 'faq.html')

TCCgo/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">

    <title>{% block titleBlock %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'general/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'general/css/bootstrap-theme.min.css.map' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'general/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'general/css/bootstrap.min.css.map' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'general/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'general/css/xeditable.css' %}">
    {% block links %}{% endblock %}

    <!--Angular is the only js that is placed here-->
    <script src="{% static 'general/js/angular.min.js' %}"></script>
    <script src="{% static 'general/js/xeditable.js' %}"></script>
  </head>
  <body ng-app="myApp">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:index' %}">TCC-go</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% if not user.is_authenticated %}
              <li><a href="{% url 'authentication:login' %}">Entrar</a></li>
              <li><a href="{% url 'authentication:register' %}">Cadastrar</a></li>
            {%endif%}
            {% if user.is_authenticated %}
              <li><a href="#">Análisar</a></li>
              <li><a href="#">Relatórios</a></li>
              <li><a href="{% url 'rules:rules_list' %}">Regras</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Trabalhos <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'text:submit_page' %}">Submeter trabalho</a></li>
                  <li><a href="{% url 'text:list_texts' %}">Consultar Trabalhos</a></li>
                  <li role="separator" class="divider"></li>
                  <!--li class="dropdown-header">Nav header</li-->
                  <li><a href="#">Contribuir</a></li>
                </ul>
              </li>
              <li><a href="{% url 'forum:forum' %}">Fórum</a></li>
            {% endif %}
              <li><a href="{% url 'faqs:faqs' %}">FAQ</a></li>
          </ul>

          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Perfil {{user.username}} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'authentication:register' %}">Editar Perfil</a></li>
                <li><a href="{% url 'authentication:password' %}">Alterar Senha</a></li>
                <li role="separator" class="divider"></li>
                <!--li class="dropdown-header">Nav header</li-->
                <li><a href="{% url 'authentication:logout' %}">Sair</a></li>
              </ul>
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}

    <script src="{% static 'general/js/jquery.min.js' %}"></script>
    <script src="{% static 'general/js/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

TCCgo/templates/faq.html
{% extends 'base.html' %}

{% block titleBlock %} TCC go | FAQ {% endblock %}

{% block content %}


<div class="container">
	<div class="row" >
		<div class="col-md-8 col-md-offset-2" style="text-align: center">
			<h3>Perguntas Frequentes </h3>
    	<br />
		</div>
	</div>
		<div id="questions_container" class="col-md-8 col-md-offset-2" ng-controller="questionController">

			<div class="panel panel-default" ng-repeat="question in questions">
					<div class="panel-heading" ng-bind="question.fields.question">
							<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse"> <span ng-bind="question.fields.question"></span></a>
							</h4>
					</div>
					<div id="collapse" class="panel-collapse collapse in" >
							<div class="panel-body">
									<span ng-bind="question.fields.answer"></span>
							</div>
					</div>
			</div>
</div>


{% endblock %}

{% block script %}
<script type="text/javascript">
var app = angular.module("myApp", []);
app.controller("questionController", function($scope, $http){
  $http.defaults.xsrfCookieName = 'csrftoken';
  $http.defaults.xsrfHeaderName = 'X-CSRFToken';

  $http.get('/faqs/all_questions').then(function(data){
    var questions = JSON.parse(data.data);
    $scope.questions = questions;
  })
});

</script>
{% endblock %}

TCCgo/templates/index.html
{% extends 'base.html' %}

{% block titleBlock %} TCC Go {% endblock %}

{% block content %}
  <h1 class="text-center text-primary">Bem vindo ao TCC Go</h1>
  <h2 class="text-center text-success">TCC go é uma ferramenta mó legal.</h2>
{% endblock %}

TCCgo/templates/login.html
{% extends 'base.html' %}

{% block titleBlock %} TCC Go {% endblock %}

{% block content %}

<div class="container" ng-controller="loginController">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h3>Login</h3>
      <hr>
    </div>
    <div class="col-md-3"></div>
  </div>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <form method="post" action="login" id="myForm" name="myForm" ng-submit="send($event)" validate>
        {% csrf_token %}
        <div class="form-group row">
          <label for="user" class="col-md-2 col-form-label">Usuário</label>
          <div class="col-md-10">
            <input type="email" class="form-control" id="email" name="email" ng-model="user.email" required placeholder="ana@email.com">
          </div>
        </div>

        <div class="form-group row">
          <label for="password" class="col-md-2 col-form-label">Senha</label>
          <div class="col-md-10">
            <input type="password" class="form-control" id="password" name="password" ng-model="user.password" required placeholder="********">
            <div style="color:red; font-size:150%" align="right" ng-if="invalid" >
              <span>Login Inválido</span>
            </div>
          </div>
        </div>


        <div class="form-group row">
          <div class="text-right">
            <button type="submit" class="btn btn-primary">Entrar</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

{% endblock %}

{% block script %}

<script src="/static/authentication/js/login.js"></script>
{% endblock %}